/* ============================================================
 * NightScribe: the website's small behaviour.
 *
 * GENERATED by website/tools/build_site.py from tools/site.js: edit the
 * source, never website/assets/main.js.
 *
 * Two jobs only, and neither is required to read the page:
 *   1. the landing remembers the language the visitor picked and, the first
 *      time, follows the language of their browser;
 *   2. the top bar marks the section you are reading.
 * ============================================================ */
(function () {
  "use strict";

  var KEY = "ns-lang";

  function store(lang) {
    try { localStorage.setItem(KEY, lang); } catch (e) { /* private mode */ }
  }

  function chosen() {
    try { return localStorage.getItem(KEY); } catch (e) { return null; }
  }

  /* ---- 1. the language ------------------------------------------------ */

  var here = document.documentElement.lang === "es" ? "es" : "en";
  var wanted = chosen();
  var preferred = (navigator.language || navigator.userLanguage || "en")
    .slice(0, 2).toLowerCase();
  if (document.body.classList.contains("landing-page")) {
    if (!wanted && preferred !== here &&
        (preferred === "es" || preferred === "en")) {
      // first visit: follow the browser, once. The switch below (and any
      // later visit) sets ns-lang, so the choice is never fought over.
      location.replace(preferred === "es" ? "index.es.html" : "index.html");
      return;
    }
  }
  Array.prototype.forEach.call(
    document.querySelectorAll("a.lang"),
    function (link) {
      link.addEventListener("click", function () {
        store(link.href.indexOf(".es.html") >= 0 ? "es" : "en");
      });
    });

  /* ---- 2. the bar marks where you are --------------------------------- */

  var links = Array.prototype.slice.call(
    document.querySelectorAll(".bar-nav a"));
  if (!links.length || !("IntersectionObserver" in window)) { return; }

  function mark(id) {
    links.forEach(function (link) {
      link.classList.toggle("on", link.getAttribute("href") === "#" + id);
    });
  }

  var seen = {};
  links.forEach(function (link) {
    var id = (link.getAttribute("href") || "").slice(1);
    if (id) { seen[id] = true; }
  });

  var observer = new IntersectionObserver(function (entries) {
    entries.forEach(function (entry) {
      if (entry.isIntersecting) { mark(entry.target.id); }
    });
  }, { rootMargin: "-25% 0px -65% 0px" });

  Array.prototype.forEach.call(
    document.querySelectorAll("section.block"),
    function (section) {
      if (seen[section.id]) { observer.observe(section); }
    });
}());
