/* ============================================================
 * NightScribe: the website's small behaviour.
 *
 * GENERATED by website/tools/build_site.py from tools/site.js: edit the
 * source, never website/assets/main.js.
 *
 * Three jobs, and none is required to read the page:
 *   1. the landing remembers the language the visitor picked and, the first
 *      time, follows the language of their browser;
 *   2. the top bar marks the section you are reading (the landing only: it
 *      is the page with a menu);
 *   3. a screenshot opens larger, with an explicit way to close it.
 *
 * Each block is independent on purpose: the viewer used to sit after the
 * menu's block, and on the guide's pages (no menu) that block returned early
 * and left the viewer unmounted, so a click there opened the raw image with
 * no way back (reported 2026-10-08).
 * ============================================================ */
(function () {
  "use strict";

  var KEY = "ns-lang";

  function store(lang) {
    try { localStorage.setItem(KEY, lang); } catch (e) { /* private mode */ }
  }

  function chosen() {
    try { return localStorage.getItem(KEY); } catch (e) { return null; }
  }

  /* ---- 1. the language ------------------------------------------------ */

  var here = document.documentElement.lang === "es" ? "es" : "en";
  var wanted = chosen();
  var preferred = (navigator.language || navigator.userLanguage || "en")
    .slice(0, 2).toLowerCase();
  if (document.body.classList.contains("landing-page") && !wanted &&
      preferred !== here && (preferred === "es" || preferred === "en")) {
    // first visit: follow the browser, once. The switch below (and any later
    // visit) sets ns-lang, so the choice is never fought over.
    location.replace(preferred === "es" ? "index.es.html" : "index.html");
    return;
  }
  Array.prototype.forEach.call(
    document.querySelectorAll("a.lang"),
    function (link) {
      link.addEventListener("click", function () {
        store(link.href.indexOf(".es.html") >= 0 ? "es" : "en");
      });
    });

  /* ---- 2. the bar marks where you are (landing only) ------------------ */

  var links = Array.prototype.slice.call(
    document.querySelectorAll(".bar-nav a"));
  if (links.length && "IntersectionObserver" in window) {
    (function () {
      function mark(id) {
        links.forEach(function (link) {
          link.classList.toggle("on",
                                link.getAttribute("href") === "#" + id);
        });
      }
      var seen = {};
      links.forEach(function (link) {
        var id = (link.getAttribute("href") || "").slice(1);
        if (id) { seen[id] = true; }
      });
      var observer = new IntersectionObserver(function (entries) {
        entries.forEach(function (entry) {
          if (entry.isIntersecting) { mark(entry.target.id); }
        });
      }, { rootMargin: "-25% 0px -65% 0px" });
      Array.prototype.forEach.call(
        document.querySelectorAll("section.block"),
        function (section) {
          if (seen[section.id]) { observer.observe(section); }
        });
    }());
  }

  /* ---- 3. a screenshot opens larger ----------------------------------- */

  var zooms = document.querySelectorAll(".shot .zoom");
  if (!zooms.length) { return; }

  var WORDS = {
    en: { close: "Close", hint: "Click anywhere to close, or press Escape." },
    es: { close: "Cerrar",
          hint: "Pincha en cualquier sitio para cerrar, o pulsa Escape." }
  };
  var L = WORDS[here];

  var box = document.createElement("div");
  box.id = "lightbox";
  box.setAttribute("role", "dialog");
  box.setAttribute("aria-modal", "true");
  box.innerHTML =
    '<button class="close" type="button" aria-label="' + L.close + '">✕' +
    '</button><img alt=""><p class="cap"></p>' +
    '<p class="hint">' + L.hint + '</p>';
  document.body.appendChild(box);
  var big = box.querySelector("img");
  var cap = box.querySelector(".cap");

  function close() {
    box.classList.remove("on");
    big.removeAttribute("src");     // the file is not kept in memory
  }

  Array.prototype.forEach.call(zooms, function (link) {
    link.addEventListener("click", function (event) {
      if (event.metaKey || event.ctrlKey || event.shiftKey) { return; }
      event.preventDefault();
      var figure = link.closest("figure");
      var text = figure ? figure.querySelector("figcaption") : null;
      big.src = link.getAttribute("href");
      big.alt = text ? text.textContent : "";
      cap.textContent = text ? text.textContent : "";
      box.classList.add("on");
    });
  });

  // Three ways out, because one is never enough: the button, a click
  // anywhere (a tap on a phone) and Escape.
  box.querySelector(".close").addEventListener("click", close);
  box.addEventListener("click", close);
  document.addEventListener("keydown", function (event) {
    if (event.key === "Escape" && box.classList.contains("on")) { close(); }
  });
}());
