############################################################
# -*- coding: utf-8 -*-
#
# NightScribe - Photometry report export module (ADR-035)
# Python  v3.12
#
# Francisco José Calvo Fernández
# (c) 2026
#
# Licence GPL v3
#
############################################################

"""Photometry report export (V-i): the project's photometry points as a
plain CSV or an AAVSO Extended File Format text, with heliocentric Julian
dates computed in-app (variables.jd_to_hjd). Quick-look points are
"indicative" (T6) and only leave the app on explicit request.
"""

import logging
from pathlib import Path

from . import followup, variables

logger = logging.getLogger(__name__)

CSV_HEADER = ("name", "hjd", "mag", "err", "filter", "comp_stars",
              "observer", "notes")


def collect_points(db, project_id, include_quicklook=False):
    # The exportable points of the project, MJD-ordered.
    # @args: include_quicklook - quick-look points are indicative (T6) and
    #        only export on explicit request
    # @return: list of point dicts
    pts = followup.list_points(db, project_id)
    return [p for p in pts
            if include_quicklook or (p.get("source") or "") != "quicklook"]


def hjd_of(point, ra_deg, dec_deg):
    # @return: the point's HJD (MJD -> JD -> HJD), or None when the instant
    #          or the coordinates are missing
    if point.get("mjd") is None or ra_deg is None or dec_deg is None:
        return None
    return variables.jd_to_hjd(point["mjd"] + variables.MJD0, ra_deg,
                               dec_deg)


def export_csv(points, out, name, ra_deg=None, dec_deg=None, observer="",
               comp_stars=None):
    # The documented group CSV (V-i): one row per point, dot decimal,
    # comma-separated, comparison stars joined by "+" in one cell.
    # @return: Path written
    comps = "+".join(comp_stars or [])
    lines = [f"# name: {name}",
             "# generated by NightScribe — dates are HJD",
             ",".join(CSV_HEADER)]
    for p in points:
        hjd = hjd_of(p, ra_deg, dec_deg)
        err = f"{p['err']:.3f}" if p.get("err") is not None else ""
        lines.append(",".join([
            name, f"{hjd:.5f}" if hjd is not None else "",
            f"{p['mag']:.3f}", err, p.get("filter") or "", comps,
            observer, ""]))
    Path(out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("photometry CSV written: %s (%d points)", out, len(points))
    return Path(out)


# ---------------- AAVSO Extended File Format ----------------

EFF_FIELDS = ("NAME,DATE,MAG,MERR,FILT,TRANS,MTYPE,CNAME,CMAG,KNAME,KMAG,"
              "AMASS,GROUP,CHART,NOTES")


def export_eff(points, out, name, ra_deg=None, dec_deg=None, obscode=""):
    # AAVSO Extended File Format (the WebObs/FotoDif interchange): header
    # lines starting with '#', then one line per point. Dates are HJD
    # (#DATE=HJD). Points without a full HJD are skipped — EFF has no
    # empty-date concept.
    # @args: obscode - the AAVSO observer code (config aavso_code)
    # @return: Path written
    lines = ["#TYPE=EXTENDED",
             f"#OBSCODE={obscode or 'UNKNOWN'}",
             "#SOFTWARE=NightScribe",
             "#DELIM=,",
             "#DATE=HJD",
             "#OBSTYPE=CCD",
             EFF_FIELDS]
    n = 0
    for p in points:
        hjd = hjd_of(p, ra_deg, dec_deg)
        if hjd is None:
            continue
        merr = f"{p['err']:.3f}" if p.get("err") is not None else "0.000"
        filt = p.get("filter") or "Clear"
        lines.append(f"{name.upper()},{hjd:.5f},{p['mag']:.3f},{merr},"
                     f"{filt},NA,STD,na,na,na,na,na,na,na,")
        n += 1
    Path(out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("photometry EFF written: %s (%d points)", out, n)
    return Path(out)


def export_report(points, out, fmt="csv", **meta):
    # Single entry point for the GUI.
    # @args: fmt - "csv" | "eff", meta - export_csv/export_eff keywords
    if fmt == "eff":
        return export_eff(points, out, **meta)
    return export_csv(points, out, **meta)
